#!/usr/bin/env python3
"""Embed the shared annotated Heart Sutra in the iOS UI test binary.

The XCUITest runner executes inside Simulator and cannot directly read the
Mac's tests/heart-sutra.annotated.txt file at runtime.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from heart_sutra import DICTIONARY, FIXTURE, candidate_positions, parse_fixture


OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "Source/Loaders/iOS-Keyboard/KeyKeyUITests/HeartSutraFixture.swift"
)


def swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def keyboard_keys() -> dict[str, str]:
    in_keyname = False
    mapping: dict[str, str] = {}
    for line in DICTIONARY.read_text(encoding="utf-8").splitlines():
        if line.strip() == "%keyname  begin":
            in_keyname = True
        elif line.strip() == "%keyname  end":
            break
        elif in_keyname:
            columns = line.split()
            if len(columns) == 2:
                mapping[columns[1]] = columns[0]
    return mapping


def render() -> str:
    _, pairs = parse_fixture(FIXTURE.read_text(encoding="utf-8"))
    ranks = candidate_positions(pairs)
    targets = [
        tokens[index + 1]
        for line in FIXTURE.read_text(encoding="utf-8").splitlines()
        for tokens in [line.split()]
        for index in range(0, len(tokens), 2)
    ]
    assert len(targets) == len(pairs) == len(ranks) == 268
    keymap = keyboard_keys()
    rows = []
    for (reading, character), target, rank in zip(pairs, targets, ranks):
        keys = "".join(keymap[symbol] for symbol in reading)
        punctuation = target[1:]
        rows.append(
            "        Entry(keys: " + swift_string(keys)
            + ", reading: " + swift_string(reading)
            + ", target: " + swift_string(character)
            + ", punctuation: " + swift_string(punctuation)
            + f", expectedRank: {rank}),"
        )
    return "\n".join([
        "// Generated by tests/generate_ios_heart_sutra_fixture.py; do not edit by hand.",
        "// The 268 ranks come from Source/DataTables/bpmf-ext.cin.",
        "enum HeartSutraFixture {",
        "    struct Entry {",
        "        let keys: String",
        "        let reading: String",
        "        let target: String",
        "        let punctuation: String",
        "        let expectedRank: Int",
        "    }",
        "",
        "    static let entries: [Entry] = [",
        *rows,
        "    ]",
        "",
        "    static var expectedText: String {",
        "        entries.map { $0.target + $0.punctuation }.joined()",
        "    }",
        "}",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated Swift is stale")
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            parser.error(f"{OUTPUT} is missing or stale; run this script without --check")
        print("PASS iOS Heart Sutra fixture: 268 readings and ranks are current")
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    print(OUTPUT)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
