// [AUTO_HEADER]

#ifndef OPENVANILLA_CONNECTION_NAME
    #define OPENVANILLA_CONNECTION_NAME         @"OpenVanilla_1_Connection"
#endif

#ifndef OPENVANILLA_DO_CONNECTION_NAME
    #define OPENVANILLA_DO_CONNECTION_NAME      @"OpenVanillaService"
#endif

#ifndef OPENVANILLA_LOADER_COMPONENT_NAME
    #define OPENVANILLA_LOADER_COMPONENT_NAME   "OpenVanilla-OSX"
#endif

#ifndef OPENVANILLA_DATABASE_COMPONENT_NAME
	#define OPENVANILLA_DATABASE_COMPONENT_NAME	"OpenVanilla-OSX-Database"
#endif

#ifndef OPENVANILLA_CEROD_DATABASE_FILE
	#define	OPENVANILLA_CEROD_DATABASE_FILE @"KeyKey.db"
#endif
