param(
    [string]$Source = (Join-Path $PSScriptRoot '../../Distributions/Takao/OnlineData/CannedMessages.plist'),
    [string]$EmojiSource = (Join-Path $PSScriptRoot '../iOS-Keyboard/KeyKeyEngine/Sources/KeyKeyEngine/BopomofoEngine.swift'),
    [string]$SupplementaryEmojiSource = (Join-Path $PSScriptRoot 'SymbolEmojiSupplement.json'),
    [string]$Output = (Join-Path $PSScriptRoot 'SymbolResources.generated.h')
)
$ErrorActionPreference = 'Stop'
$settings = [System.Xml.XmlReaderSettings]::new()
$settings.DtdProcessing = [System.Xml.DtdProcessing]::Ignore
$settings.XmlResolver = $null
$reader = [System.Xml.XmlReader]::Create((Resolve-Path $Source).Path, $settings)
$document = [System.Xml.XmlDocument]::new()
try { $document.Load($reader) } finally { $reader.Dispose() }
function Value($dict, [string]$key) {
    foreach ($node in $dict.ChildNodes) {
        if ($node.Name -eq 'key' -and $node.InnerText -eq $key) { return $node.NextSibling }
    }
    return $null
}
function Literal([string]$text) {
    # ASCII-only UTF-16 literals make MSVC source code-page settings irrelevant.
    $result = 'L"'
    foreach ($c in $text.ToCharArray()) {
        $v = [int]$c
        if ($v -eq 34) { $result += '\"' }
        elseif ($v -eq 92) { $result += '\\' }
        elseif ($v -ge 32 -and $v -le 126) { $result += $c }
        else { $result += ('\x{0:X4}' -f $v) + '" L"' }
    }
    return $result + '"'
}
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by Generate-SymbolResources.ps1. Do not edit.')
$lines.Add('// Symbols: Source/Distributions/Takao/OnlineData/CannedMessages.plist')
$hasher = [System.Security.Cryptography.SHA256]::Create()
try { $sourceHash = [BitConverter]::ToString($hasher.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path $Source).Path))).Replace('-', '').ToLowerInvariant() }
finally { $hasher.Dispose() }
$lines.Add('// Source SHA-256: ' + $sourceHash)
$emojiContent = [IO.File]::ReadAllText((Resolve-Path $EmojiSource).Path, [Text.Encoding]::UTF8)
$emojiMatch = [regex]::Match($emojiContent, '(?s)public static let emojis: \[String\] = \[(.*?)\]')
if (!$emojiMatch.Success) { throw 'Mobile emoji declaration not found' }
$emojiMatches = [regex]::Matches($emojiMatch.Groups[1].Value, '"([^"\\]*)"')
$remainder = [regex]::Replace($emojiMatch.Groups[1].Value, '"([^"\\]*)"|\s|,', '')
$emojis = @($emojiMatches | ForEach-Object { $_.Groups[1].Value })
$emojiUnique = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach ($emoji in $emojis) { $null = $emojiUnique.Add($emoji) }
if ($remainder -ne '' -or $emojis.Count -ne 90 -or $emojiUnique.Count -ne 90) {
    throw 'Mobile emoji declaration must contain exactly 90 unique unescaped strings'
}
$lines.Add('// Emoji: Source/Loaders/iOS-Keyboard/KeyKeyEngine/Sources/KeyKeyEngine/BopomofoEngine.swift')
$hasher = [Security.Cryptography.SHA256]::Create()
try { $emojiHash = [BitConverter]::ToString($hasher.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path $EmojiSource).Path))).Replace('-', '').ToLowerInvariant() }
finally { $hasher.Dispose() }
$lines.Add('// Emoji source SHA-256: ' + $emojiHash)
$supplement = ConvertFrom-Json -InputObject ([IO.File]::ReadAllText((Resolve-Path $SupplementaryEmojiSource).Path, [Text.Encoding]::UTF8))
if ($supplement.Count -ne 110) { throw 'Windows emoji supplement must contain exactly 110 entries' }
foreach ($emoji in $supplement) {
    if ($emoji -isnot [string] -or $emoji.Length -eq 0) { throw 'Windows emoji supplement entries must be nonempty strings' }
}
$emojis += $supplement
foreach ($emoji in $supplement) {
    if (!$emojiUnique.Add($emoji)) { throw 'Mobile and Windows emoji entries must be 200 unique strings' }
}
if ($emojis.Count -ne 200 -or $emojiUnique.Count -ne 200) { throw 'Mobile and Windows emoji entries must be 200 unique strings' }
$lines.Add('// Windows emoji supplement: Source/Loaders/Windows-TSF/SymbolEmojiSupplement.json')
$hasher = [Security.Cryptography.SHA256]::Create()
try { $supplementHash = [BitConverter]::ToString($hasher.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path $SupplementaryEmojiSource).Path))).Replace('-', '').ToLowerInvariant() }
finally { $hasher.Dispose() }
$lines.Add('// Windows emoji supplement SHA-256: ' + $supplementHash)
$lines.Add('#pragma once')
$lines.Add('#include "SymbolResources.h"')
$lines.Add('namespace KeyKey::WindowsTsf {')
$lines.Add('inline const std::vector<SymbolCategory>& BuiltinSymbolCategories() {')
$lines.Add('    static const std::vector<SymbolCategory> categories = {')
$categories = Value $document.plist.dict 'CannedMessages'
foreach ($category in $categories.ChildNodes) {
    if ($category.Name -ne 'dict') { continue }
    $names = Value $category 'Name'
    $name = Value $names 'zh_TW'
    if (!$name) { $name = Value $names 'en' }
    if (!$name) { throw 'Missing category name' }
    $isGrid = Value $category 'IsSymbolButtonList'
    $layout = if ($isGrid -and $isGrid.InnerText -eq 'true') { 'Grid' } else { 'List' }
    $lines.Add('        {' + (Literal $name.InnerText) + ', SymbolLayout::' + $layout + ', {')
    $buttons = Value $category 'Buttons'
    foreach ($button in $buttons.ChildNodes) {
        if ($button.Name -eq 'string') {
            $literal = Literal $button.InnerText
            $lines.Add('            {' + $literal + ', ' + $literal + '},')
        }
    }
    $messages = Value $category 'Messages'
    foreach ($message in $messages.ChildNodes) {
        if ($message.Name -ne 'dict') { continue }
        $label = Value $message 'Name'
        $text = Value $message 'Text'
        if (!$text) { throw 'Missing message text' }
        if (!$label) { $label = $text }
        $lines.Add('            {' + (Literal $label.InnerText) + ', ' + (Literal $text.InnerText) + '},')
    }
    $lines.Add('        }},')
}
$lines.Add('        {L"Emoji", SymbolLayout::Grid, {')
foreach ($emoji in $emojis) {
    $literal = Literal $emoji
    $lines.Add('            {' + $literal + ', ' + $literal + '},')
}
$lines.Add('        }, true},')
$lines.Add('    };')
$lines.Add('    return categories;')
$lines.Add('}')
$lines.Add('} // namespace KeyKey::WindowsTsf')
[System.IO.File]::WriteAllLines($Output, $lines, [System.Text.UTF8Encoding]::new($false))
