param(
    [string]$Source = (Join-Path $PSScriptRoot '../../Distributions/Takao/OnlineData/CannedMessages.plist'),
    [string]$Output = (Join-Path $PSScriptRoot 'SymbolResources.generated.h')
)
$ErrorActionPreference = 'Stop'
$settings = [System.Xml.XmlReaderSettings]::new()
$settings.DtdProcessing = [System.Xml.DtdProcessing]::Ignore
$settings.XmlResolver = $null
$reader = [System.Xml.XmlReader]::Create((Resolve-Path $Source).Path, $settings)
$document = [System.Xml.XmlDocument]::new()
try { $document.Load($reader) } finally { $reader.Dispose() }
function Value($dict, [string]$key) {
    foreach ($node in $dict.ChildNodes) {
        if ($node.Name -eq 'key' -and $node.InnerText -eq $key) { return $node.NextSibling }
    }
    return $null
}
function Literal([string]$text) {
    # ASCII-only UTF-16 literals make MSVC source code-page settings irrelevant.
    $result = 'L"'
    foreach ($c in $text.ToCharArray()) {
        $v = [int]$c
        if ($v -eq 34) { $result += '\"' }
        elseif ($v -eq 92) { $result += '\\' }
        elseif ($v -ge 32 -and $v -le 126) { $result += $c }
        else { $result += ('\x{0:X4}' -f $v) + '" L"' }
    }
    return $result + '"'
}
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// Generated by Generate-SymbolResources.ps1 from CannedMessages.plist. Do not edit.')
$hasher = [System.Security.Cryptography.SHA256]::Create()
try { $sourceHash = [BitConverter]::ToString($hasher.ComputeHash([IO.File]::ReadAllBytes((Resolve-Path $Source).Path))).Replace('-', '').ToLowerInvariant() }
finally { $hasher.Dispose() }
$lines.Add('// Source SHA-256: ' + $sourceHash)
$lines.Add('#pragma once')
$lines.Add('#include "SymbolResources.h"')
$lines.Add('namespace KeyKey::WindowsTsf {')
$lines.Add('inline const std::vector<SymbolCategory>& BuiltinSymbolCategories() {')
$lines.Add('    static const std::vector<SymbolCategory> categories = {')
$categories = Value $document.plist.dict 'CannedMessages'
foreach ($category in $categories.ChildNodes) {
    if ($category.Name -ne 'dict') { continue }
    $names = Value $category 'Name'
    $name = Value $names 'zh_TW'
    if (!$name) { $name = Value $names 'en' }
    if (!$name) { throw 'Missing category name' }
    $lines.Add('        {' + (Literal $name.InnerText) + ', {')
    $buttons = Value $category 'Buttons'
    foreach ($button in $buttons.ChildNodes) {
        if ($button.Name -eq 'string') {
            $literal = Literal $button.InnerText
            $lines.Add('            {' + $literal + ', ' + $literal + '},')
        }
    }
    $messages = Value $category 'Messages'
    foreach ($message in $messages.ChildNodes) {
        if ($message.Name -ne 'dict') { continue }
        $label = Value $message 'Name'
        $text = Value $message 'Text'
        if (!$text) { throw 'Missing message text' }
        if (!$label) { $label = $text }
        $lines.Add('            {' + (Literal $label.InnerText) + ', ' + (Literal $text.InnerText) + '},')
    }
    $lines.Add('        }},')
}
$lines.Add('    };')
$lines.Add('    return categories;')
$lines.Add('}')
$lines.Add('} // namespace KeyKey::WindowsTsf')
[System.IO.File]::WriteAllLines($Output, $lines, [System.Text.UTF8Encoding]::new($false))
