<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KeyKeySettings</AssemblyName>
    <Version>1.3.0</Version>
    <ApplicationIcon>../chichi77.ico</ApplicationIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <NoWarn>$(NoWarn);WPF0001</NoWarn>
  </PropertyGroup>
</Project>
