#!/usr/bin/env bash
set -euo pipefail

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
linux_dir=$(CDPATH='' cd -- "$script_dir/.." && pwd)
test_root=${KEYKEY_CONFIGURE_TEST_ROOT:-$linux_dir/out/source-test}
mode=${1:---all}
makefile_marker='# Generated by chichi77 KeyKey configure. Run make distclean to remove.'

case "$mode" in
  --all|--source-directory-only|--out-of-source-only) ;;
  *)
    echo "Usage: ci/test-configure-make.sh [--all|--source-directory-only|--out-of-source-only]" >&2
    exit 2
    ;;
esac

case "$test_root" in
  /*) ;;
  *) test_root="$linux_dir/$test_root" ;;
esac
case "$test_root" in
  "$linux_dir"/out/*) ;;
  *)
    echo "KEYKEY_CONFIGURE_TEST_ROOT must be a child of the Linux out directory." >&2
    exit 2
    ;;
esac

cleanup_source_build() {
  if [[ -f "$linux_dir/Makefile" ]] &&
      head -n 1 "$linux_dir/Makefile" | grep -Fqx "$makefile_marker"; then
    make -C "$linux_dir" distclean >/dev/null
  fi
}

cleanup() {
  cleanup_source_build
  cmake -E remove_directory "$linux_dir/out/build/configure-make-preserve"
}
trap cleanup EXIT

cmake -E remove_directory "$test_root"
mkdir -p "$test_root"

cache_value() {
  local cache_file=$1
  local variable_name=$2
  sed -n "s/^${variable_name}:[^=]*=//p" "$cache_file"
}

layout_value() {
  local layout_file=$1
  local variable_name=$2
  sed -n "s/^${variable_name}=//p" "$layout_file"
}

assert_installed_tree() {
  local stage=$1
  local prefix=$2
  local libdir=$3
  local datadir=$4
  local root="$stage$prefix"
  local addon="$root/$libdir/fcitx5/chichi77-keykey.so"
  local data_root="$root/$datadir/chichi77-keykey/data"

  test -f "$addon"
  test -f "$root/$datadir/fcitx5/addon/chichi77-keykey.conf"
  test -f "$root/$datadir/fcitx5/inputmethod/chichi77-keykey-bopomofo.conf"
  test -f "$root/$datadir/fcitx5/inputmethod/chichi77-keykey-cangjie.conf"
  test -f "$root/$datadir/fcitx5/inputmethod/chichi77-keykey-simplex.conf"
  test -f "$data_root/bpmf-ext.cin"
  test -f "$data_root/cj-ext.cin"
  test -f "$data_root/simplex-ext.cin"
  test -f "$data_root/bpmf-punctuations.cin"
  test -f "$data_root/tc2sc.cin"
  test -f "$data_root/associated-phrases/McBopomofo.occ"
  test -f "$data_root/associated-phrases/display-names.tsv"
  test "$(find "$data_root/associated-phrases" -maxdepth 1 \
    -type f -name 'phrase.*.tsv' | wc -l)" -eq 29
  test -f "$root/$datadir/doc/chichi77-keykey/LICENSE-linux-frontend.txt"
  test -f "$root/$datadir/doc/chichi77-keykey/LICENSE-MIT.txt"
  test -f "$root/$datadir/doc/chichi77-keykey/LICENSE-yahoo-bsd.txt"
  test -f "$root/$datadir/doc/chichi77-keykey/LICENSE-McBopomofo.txt"
  test -f "$root/$datadir/doc/chichi77-keykey/LICENSE-associated-phrase-collections.txt"

  ldd "$addon"
  if ldd "$addon" | grep -q 'not found'; then
    echo "The source-built addon has unresolved dependencies." >&2
    exit 1
  fi
  if ! nm -D --defined-only "$addon" |
      awk '$3 == "fcitx_addon_factory_instance" { found = 1 } END { exit !found }'; then
    echo "The source-built addon does not export the Fcitx factory symbol." >&2
    exit 1
  fi
  strings "$addon" |
    grep -F "$prefix/$datadir/chichi77-keykey/data" >/dev/null
  if strings "$addon" | grep -F "$stage" >/dev/null; then
    echo "DESTDIR leaked into the source-built addon." >&2
    exit 1
  fi
}

assert_manifest_removed() {
  local stage=$1
  local manifest=$2
  local installed_file

  while IFS= read -r installed_file; do
    if [[ -e "$stage$installed_file" || -L "$stage$installed_file" ]]; then
      echo "Uninstall left a manifest file behind: $stage$installed_file" >&2
      exit 1
    fi
  done <"$manifest"
}

test_help_and_errors() {
  "$linux_dir/configure" --help | grep -Fq -- '--prefix=PATH'

  if "$linux_dir/configure" --unknown-source-build-option \
      >"$test_root/unknown-option.log" 2>&1; then
    echo "configure accepted an unknown option." >&2
    exit 1
  fi
  grep -Fq 'unknown option' "$test_root/unknown-option.log"

  local collision_dir="$test_root/existing Makefile"
  mkdir -p "$collision_dir"
  printf 'all:\n\t@true\n' >"$collision_dir/Makefile"
  if (cd "$collision_dir" && "$linux_dir/configure" --disable-fcitx5) \
      >"$test_root/existing-makefile.log" 2>&1; then
    echo "configure overwrote an existing Makefile." >&2
    exit 1
  fi
  grep -Fq 'refusing to overwrite' "$test_root/existing-makefile.log"

  local missing_compiler_dir="$test_root/missing compiler"
  mkdir -p "$missing_compiler_dir"
  if (cd "$missing_compiler_dir" &&
      CXX=/definitely/missing/keykey-cxx \
        "$linux_dir/configure" --disable-fcitx5) \
      >"$test_root/missing-compiler.log" 2>&1; then
    echo "configure accepted a missing requested compiler." >&2
    exit 1
  fi
  grep -Eq 'CMAKE_CXX_COMPILER|compiler.*not found|not a full path' \
    "$test_root/missing-compiler.log"

  if "$linux_dir/configure" --disable-tests --enable-x11-e2e-host \
      >"$test_root/incompatible-options.log" 2>&1; then
    echo "configure accepted an X11 test host with tests disabled." >&2
    exit 1
  fi
  grep -Fq 'requires --enable-tests' "$test_root/incompatible-options.log"
}

test_source_directory_build() {
  local stage="$test_root/source stage"
  local build_dir="$linux_dir/out/build/configure-make"
  local cache="$build_dir/CMakeCache.txt"
  local layout="$build_dir/keykey-install-layout.txt"
  local manifest="$build_dir/install_manifest.txt"
  local libdir
  local datadir
  local preserved="$linux_dir/out/build/configure-make-preserve/sentinel"

  cleanup_source_build
  (
    cd "$linux_dir"
    ./configure --prefix=/usr
    make -j2
    make check
  )

  libdir=$(layout_value "$layout" libdir)
  datadir=$(layout_value "$layout" datadir)
  test -n "$libdir"
  test -n "$datadir"

  cmake -E remove_directory "$stage"
  mkdir -p "$stage/usr/$datadir/chichi77-keykey/data"
  touch "$stage/usr/$datadir/chichi77-keykey/data/preserve-user-file"
  (
    cd "$linux_dir"
    make DESTDIR="$stage" install
  )
  assert_installed_tree "$stage" /usr "$libdir" "$datadir"
  test -s "$manifest"
  if grep -Fq "$stage" "$manifest"; then
    echo "DESTDIR leaked into the install manifest." >&2
    exit 1
  fi
  cp "$manifest" "$test_root/source-install-manifest.txt"

  (
    cd "$linux_dir"
    make DESTDIR="$stage" uninstall
  )
  assert_manifest_removed "$stage" "$manifest"
  test -f "$stage/usr/$datadir/chichi77-keykey/data/preserve-user-file"

  (
    cd "$linux_dir"
    make clean
    test -f "$build_dir/CMakeCache.txt"
    make -j2
    make check
  )

  mkdir -p "$(dirname -- "$preserved")"
  touch "$preserved"
  make -C "$linux_dir" distclean
  test ! -e "$linux_dir/Makefile"
  test ! -e "$build_dir"
  test -f "$preserved"
}

test_out_of_source_build() {
  local build_root="$test_root/out of source build"
  local inner_build="$build_root/.keykey-configure-build"
  local cache="$inner_build/CMakeCache.txt"
  local layout="$inner_build/keykey-install-layout.txt"
  local stage="$test_root/custom stage"
  local prefix='/opt/chichi77 keykey'
  local libdir=lib-custom
  local datadir=share-custom
  local manifest="$inner_build/install_manifest.txt"

  mkdir -p "$build_root"
  (
    cd "$build_root"
    CPPFLAGS=-DKEYKEY_CONFIGURE_OLD_CPP=1 \
    CXXFLAGS='-O0 -DKEYKEY_CONFIGURE_OLD_CXX=1' \
    LDFLAGS=-Wl,--as-needed \
      "$linux_dir/configure" \
        --prefix=/opt/keykey-old \
        --libdir=lib-old \
        --datadir=share-old

    CPPFLAGS=-DKEYKEY_CONFIGURE_CPP=1 \
    CXXFLAGS='-O1 -DKEYKEY_CONFIGURE_CXX=1' \
    LDFLAGS=-Wl,--as-needed \
      "$linux_dir/configure" \
        --prefix="$prefix" \
        --libdir="$libdir" \
        --datadir="$datadir"
  )

  test "$(cache_value "$cache" CMAKE_INSTALL_PREFIX)" = "$prefix"
  test "$(layout_value "$layout" libdir)" = "$libdir"
  test "$(layout_value "$layout" datadir)" = "$datadir"
  grep -Fq 'CMAKE_CXX_FLAGS:STRING=-DKEYKEY_CONFIGURE_CPP=1 -O1 -DKEYKEY_CONFIGURE_CXX=1' \
    "$cache"
  if grep -Fq 'KEYKEY_CONFIGURE_OLD' "$cache"; then
    echo "configure retained flags from an earlier configuration." >&2
    exit 1
  fi

  (
    cd "$build_root"
    make -j2
    make check
  )

  cmake -E remove_directory "$stage"
  mkdir -p "$stage$prefix/$datadir/chichi77-keykey/data"
  touch "$stage$prefix/$datadir/chichi77-keykey/data/preserve-user-file"
  (
    cd "$build_root"
    make DESTDIR="$stage" install
  )
  assert_installed_tree "$stage" "$prefix" "$libdir" "$datadir"
  test -s "$manifest"
  cp "$manifest" "$test_root/custom-install-manifest.txt"

  (
    cd "$build_root"
    make DESTDIR="$stage" uninstall
  )
  assert_manifest_removed "$stage" "$manifest"
  test -f "$stage$prefix/$datadir/chichi77-keykey/data/preserve-user-file"

  (
    cd "$build_root"
    make distclean
  )
  test ! -e "$build_root/Makefile"
  test ! -e "$inner_build"
}

test_help_and_errors
case "$mode" in
  --all)
    test_source_directory_build
    test_out_of_source_build
    ;;
  --source-directory-only) test_source_directory_build ;;
  --out-of-source-only) test_out_of_source_build ;;
esac

source_revision=${KEYKEY_SOURCE_REVISION:-unknown}
if [[ "$source_revision" == unknown ]] &&
    git -C "$linux_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  source_revision=$(git -C "$linux_dir" rev-parse HEAD)
fi
source_manifest_report=not-run
custom_manifest_report=not-run
if [[ -f "$test_root/source-install-manifest.txt" ]]; then
  source_manifest_report=$test_root/source-install-manifest.txt
fi
if [[ -f "$test_root/custom-install-manifest.txt" ]]; then
  custom_manifest_report=$test_root/custom-install-manifest.txt
fi

cat >"$test_root/result.txt" <<EOF
buildMethod=configure-make
sourceDirectory=$linux_dir
sourceRevision=$source_revision
cmakeVersion=$(cmake --version | head -n 1)
makeVersion=$(make --version | head -n 1)
compilerVersion=$(c++ --version | head -n 1)
mode=$mode
sourceInstallManifest=$source_manifest_report
customInstallManifest=$custom_manifest_report
result=passed
EOF

printf 'configure/GNU Make source build passed; report: %s\n' \
  "$test_root/result.txt"
