#!/usr/bin/env python3
"""Keep the standalone five-platform image identical to Google Play page 05.

The selected v1.3.0 artwork is generated by generate-assets.swift. This helper
remains for the former entry point without recreating the outdated Linux card.
"""
from pathlib import Path
from shutil import copyfile

store = Path(__file__).resolve().parent
source = store / "GooglePlay" / "Phone" / "05.png"
destination = store / "FivePlatforms" / "five-platforms.png"
if not source.is_file():
    raise SystemExit(f"Missing {source}; run StoreAssets/generate-assets.swift first")
destination.parent.mkdir(parents=True, exist_ok=True)
copyfile(source, destination)
print(destination.relative_to(store))
